/*
 * Copyright (c) 2012-2020 Abdul-Mujeeb Aliu for ekoVPN
 * Distributed under the GNU GPL v2 with additional terms. For full terms see the file doc/LICENSE.txt
 */

// Generated by Dagger (https://dagger.dev).
package com.ekovpn.android.data.cache.vpn;

import android.content.Context;
import dagger.internal.Factory;
import de.blinkt.openvpn.core.ProfileManager;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class OVPNProfileManager_Factory implements Factory<OVPNProfileManager> {
  private final Provider<Context> contextProvider;

  private final Provider<ProfileManager> profileManagerProvider;

  public OVPNProfileManager_Factory(Provider<Context> contextProvider,
      Provider<ProfileManager> profileManagerProvider) {
    this.contextProvider = contextProvider;
    this.profileManagerProvider = profileManagerProvider;
  }

  @Override
  public OVPNProfileManager get() {
    return newInstance(contextProvider.get(), profileManagerProvider.get());
  }

  public static OVPNProfileManager_Factory create(Provider<Context> contextProvider,
      Provider<ProfileManager> profileManagerProvider) {
    return new OVPNProfileManager_Factory(contextProvider, profileManagerProvider);
  }

  public static OVPNProfileManager newInstance(Context context, ProfileManager profileManager) {
    return new OVPNProfileManager(context, profileManager);
  }
}
