/*
 * Copyright (c) 2012-2020 Abdul-Mujeeb Aliu for ekoVPN
 * Distributed under the GNU GPL v2 with additional terms. For full terms see the file doc/LICENSE.txt
 */

// Generated by Dagger (https://dagger.dev).
package com.ekovpn.android.data.repositories.ads;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AdsRepositoryImpl_Factory implements Factory<AdsRepositoryImpl> {
  private final Provider<Context> contextProvider;

  public AdsRepositoryImpl_Factory(Provider<Context> contextProvider) {
    this.contextProvider = contextProvider;
  }

  @Override
  public AdsRepositoryImpl get() {
    return newInstance(contextProvider.get());
  }

  public static AdsRepositoryImpl_Factory create(Provider<Context> contextProvider) {
    return new AdsRepositoryImpl_Factory(contextProvider);
  }

  public static AdsRepositoryImpl newInstance(Context context) {
    return new AdsRepositoryImpl(context);
  }
}
